/**
 * OS NOMES DAS HABILIDADES EM PORTUGUES (08/09/2026 — reporte do dono: o balao
 * de conjuracao mostrava "First Aid !!"; "tudo precisa estar no portugues").
 *
 * Gerado a partir de `assets-build/ui/nomes-de-habilidade.json` do servidor
 * (o `skillnametable` do cliente oficial em PT-BR, extraido por
 * `tools/skill-name`): 355 nomes, chaveados pelo NOME CONSTANTE da habilidade
 * (`SkillInfo[id].Name`), que e o que os dois lados compartilham. Quem nao
 * esta aqui cai no `SkillName` ingles do SkillInfo — nunca em vazio.
 *
 * NAO EDITE A MAO: regenere quando o pacote mudar (D-974).
 */
import SkillInfo from './SkillInfo.js';

const NOME_PT_POR_CONSTANTE = {
	"AC_CHARGEARROW": "Disparo Violento",
	"AC_CONCENTRATION": "Concentrar",
	"AC_DOUBLE": "Rajada de Flechas",
	"AC_MAKINGARROW": "Fabricar Flechas",
	"AC_OWL": "Olhos de Coruja",
	"AC_SHOWER": "Chuva de Flechas",
	"AC_VULTURE": "Olhos de Águia",
	"ALL_BUYING_STORE": "Loja de Compras",
	"ALL_RESURRECTION": "Ressuscitar",
	"AL_ANGELUS": "Angelus",
	"AL_BLESSING": "Bênção",
	"AL_CRUCIS": "Signum Crucis",
	"AL_CURE": "Medicar",
	"AL_DECAGI": "Diminuir Agilidade",
	"AL_DEMONBANE": "Flagelo do Mal",
	"AL_DP": "Proteção Divina",
	"AL_HEAL": "Curar",
	"AL_HOLYLIGHT": "Luz Divina",
	"AL_HOLYWATER": "Aqua Benedicta",
	"AL_INCAGI": "Aumentar Agilidade",
	"AL_PNEUMA": "Escudo Sagrado",
	"AL_RUWACH": "Revelação",
	"AL_TELEPORT": "Teleporte",
	"AL_WARP": "Portal",
	"AM_ACIDTERROR": "Terror Ácido",
	"AM_AXEMASTERY": "Perícia com Machado e Espada",
	"AM_BIOETHICS": "Bioética",
	"AM_CALLHOMUN": "Despertar Homunculus",
	"AM_CANNIBALIZE": "Criar Monstro Planta",
	"AM_CP_ARMOR": "Revestir Armadura",
	"AM_CP_HELM": "Revestir Capacete",
	"AM_CP_SHIELD": "Revestir Escudo",
	"AM_CP_WEAPON": "Revestir Arma",
	"AM_DEMONSTRATION": "Fogo Grego",
	"AM_LEARNINGPOTION": "Pesquisa de Poções",
	"AM_PHARMACY": "Preparar Poção",
	"AM_POTIONPITCHER": "Arremessar Poção",
	"AM_REST": "Vaporizar",
	"AM_RESURRECTHOMUN": "Ressuscitar Homunculus",
	"AM_SPHEREMINE": "Criar Esfera Marinha",
	"ASC_BREAKER": "Destruidor de Almas",
	"ASC_CDP": "Criar Veneno Mortal",
	"ASC_EDP": "Encantar com Veneno Mortal",
	"ASC_KATAR": "Perícia com Katar Avançada",
	"ASC_METEORASSAULT": "Impacto Meteoro",
	"AS_CLOAKING": "Furtividade",
	"AS_ENCHANTPOISON": "Envenenar Arma",
	"AS_GRIMTOOTH": "Tocaia",
	"AS_KATAR": "Perícia com Katar",
	"AS_LEFT": "Perícia com Mão Esquerda",
	"AS_POISONREACT": "Refletir Veneno",
	"AS_RIGHT": "Perícia com Mão Direita",
	"AS_SONICACCEL": "Lâminas Aceleradas",
	"AS_SONICBLOW": "Lâminas Destruidoras",
	"AS_SPLASHER": "Explosão Tóxica",
	"AS_VENOMDUST": "Névoa Tóxica",
	"AS_VENOMKNIFE": "Faca Envenenada",
	"BA_APPLEIDUN": "Maçãs de Idun",
	"BA_ASSASSINCROSS": "Crepúsculo Sangrento",
	"BA_DISSONANCE": "Dissonância",
	"BA_MUSICALLESSON": "Lições de Música",
	"BA_MUSICALSTRIKE": "Flecha Melódica",
	"BA_PANGVOICE": "Voz Dolorosa",
	"BA_POEMBRAGI": "Poema de Bragi",
	"BA_WHISTLE": "Assovio",
	"BD_ADAPTATION": "Aquecimento",
	"BD_DRUMBATTLEFIELD": "Rufar dos Tambores",
	"BD_ENCORE": "Bis",
	"BD_ETERNALCHAOS": "Ritmo Caótico",
	"BD_INTOABYSS": "Canção Preciosa",
	"BD_LULLABY": "Cantiga de Ninar",
	"BD_RICHMANKIM": "Banquete de Njord",
	"BD_RINGNIBELUNGEN": "Anel dos Nibelungos",
	"BD_ROKISWEIL": "Lamento de Loki",
	"BD_SIEGFRIED": "Ode a Siegfried",
	"BS_ADRENALINE": "Adrenalina Pura",
	"BS_AXE": "Forjar Machado",
	"BS_DAGGER": "Forjar Adaga",
	"BS_ENCHANTEDSTONE": "Produzir Pedra Fundamental",
	"BS_FINDINGORE": "Encontrar Minério",
	"BS_GREED": "Ganância",
	"BS_HAMMERFALL": "Martelo de Thor",
	"BS_HILTBINDING": "Punho Firme",
	"BS_IRON": "Trabalhar Ferro",
	"BS_KNUCKLE": "Forjar Soqueira",
	"BS_MACE": "Forjar Maça",
	"BS_MAXIMIZE": "Amplificar Poder",
	"BS_ORIDEOCON": "Perícia com Oridecon",
	"BS_OVERTHRUST": "Força Violenta",
	"BS_REPAIRWEAPON": "Consertar Armas",
	"BS_SKINTEMPER": "Resistência ao Fogo",
	"BS_SPEAR": "Forjar Lança",
	"BS_STEEL": "Trabalhar Aço",
	"BS_SWORD": "Forjar Espada",
	"BS_TWOHANDSWORD": "Forjar Espada de Duas Mãos",
	"BS_UNFAIRLYTRICK": "Venda Duvidosa",
	"BS_WEAPONPERFECT": "Manejo Perfeito",
	"BS_WEAPONRESEARCH": "Perícia em Armamento",
	"CG_ARROWVULCAN": "Vulcão de Flechas",
	"CG_HERMODE": "Bastão de Hermod",
	"CG_MARIONETTE": "Controle de Marionete",
	"CG_MOONLIT": "Bênção Protetora",
	"CG_SPECIALSINGER": "Vocação Musical",
	"CG_TAROTCARD": "Destino nas Cartas",
	"CH_CHAINCRUSH": "Combo Esmagador",
	"CH_PALMSTRIKE": "Golpe da Palma em Fúria",
	"CH_SOULCOLLECT": "Zen",
	"CH_TIGERFIST": "Punho do Tigre",
	"CR_ACIDDEMONSTRATION": "Bomba Ácida",
	"CR_AUTOGUARD": "Bloqueio",
	"CR_DEFENDER": "Aura Sagrada",
	"CR_DEVOTION": "Redenção",
	"CR_FULLPROTECTION": "Proteção Química Total",
	"CR_GRANDCROSS": "Crux Magnum",
	"CR_HOLYCROSS": "Crux Divinum",
	"CR_PROVIDENCE": "Divina Providência",
	"CR_REFLECTSHIELD": "Escudo Refletor",
	"CR_SHIELDBOOMERANG": "Escudo Bumerangue",
	"CR_SHIELDCHARGE": "Punição Divina",
	"CR_SHRINK": "Submissão",
	"CR_SLIMPITCHER": "Arremessar Poção Compacta",
	"CR_SPEARQUICKEN": "Rapidez com Lança",
	"CR_TRUST": "Fé",
	"DC_DANCINGLESSON": "Lições de Dança",
	"DC_DONTFORGETME": "Não Me Abandones",
	"DC_FORTUNEKISS": "Beijo da Sorte",
	"DC_HUMMING": "Sibilo",
	"DC_SCREAM": "Escândalo",
	"DC_SERVICEFORYOU": "Dança Cigana",
	"DC_THROWARROW": "Estilingue",
	"DC_UGLYDANCE": "Dança do Ventre",
	"DC_WINKCHARM": "Piscadela",
	"GS_DUST": "Controle de Multidão",
	"GS_SPREADATTACK": "Disparo Espalhado",
	"HP_ASSUMPTIO": "Assumptio",
	"HP_BASILICA": "Basílica",
	"HP_MANARECHARGE": "Riqueza Espírito",
	"HP_MEDITATIO": "Meditatio",
	"HT_ANKLESNARE": "Instalar Armadilha",
	"HT_BEASTBANE": "Flagelo das Feras",
	"HT_BLASTMINE": "Instalar Mina",
	"HT_BLITZBEAT": "Ataque Aéreo",
	"HT_CLAYMORETRAP": "Armadilha Explosiva",
	"HT_DETECTING": "Alerta",
	"HT_FALCON": "Adestrar Ave",
	"HT_FLASHER": "Armadilha Luminosa",
	"HT_FREEZINGTRAP": "Armadilha Congelante",
	"HT_LANDMINE": "Armadilha Atordoante",
	"HT_PHANTASMIC": "Flecha Ilusória",
	"HT_REMOVETRAP": "Remover Armadilha",
	"HT_SANDMAN": "Armadilha Sonífera",
	"HT_SHOCKWAVE": "Armadilha Extenuante",
	"HT_SKIDTRAP": "Armadilha Escorregadia",
	"HT_SPRINGTRAP": "Desativar Armadilha",
	"HT_STEELCROW": "Garras de Aço",
	"HT_TALKIEBOX": "Mensagem Secreta",
	"HW_GANBANTEIN": "Ganbantein",
	"HW_GRAVITATION": "Campo Gravitacional",
	"HW_MAGICCRASHER": "Esmagamento Mágico",
	"HW_MAGICPOWER": "Amplificação Mística",
	"HW_NAPALMVULCAN": "Vulcão Napalm",
	"HW_SOULDRAIN": "Dreno de Alma",
	"KN_AUTOCOUNTER": "Contra-Ataque",
	"KN_BOWLINGBASH": "Impacto de Tyr",
	"KN_BRANDISHSPEAR": "Brandir Lança",
	"KN_CAVALIERMASTERY": "Perícia em Montaria",
	"KN_CHARGEATK": "Avanço Ofensivo",
	"KN_PIERCE": "Perfurar",
	"KN_RIDING": "Montaria",
	"KN_SPEARBOOMERANG": "Lança Bumerangue",
	"KN_SPEARMASTERY": "Perícia com Lança",
	"KN_SPEARSTAB": "Estocada",
	"KN_TWOHANDQUICKEN": "Rapidez com Duas Mãos",
	"LK_AURABLADE": "Lâmina de Aura",
	"LK_BERSERK": "Frenesi",
	"LK_CONCENTRATION": "Dedicação",
	"LK_HEADCRUSH": "Golpe Traumático",
	"LK_JOINTBEAT": "Ataque Vital",
	"LK_PARRYING": "Aparar Golpe",
	"LK_SPIRALPIERCE": "Perfurar em Espiral",
	"LK_TENSIONRELAX": "Relaxar",
	"MC_CARTDECORATE": "Decorar Carrinho",
	"MC_CARTREVOLUTION": "Cavalo-de-Pau",
	"MC_CHANGECART": "Personalizar Carrinho",
	"MC_DISCOUNT": "Desconto",
	"MC_IDENTIFY": "Identificar Item",
	"MC_INCCARRY": "Aumentar Capacidade de Carga",
	"MC_LOUD": "Grito de Guerra",
	"MC_MAMMONITE": "Mammonita",
	"MC_OVERCHARGE": "Superfaturar",
	"MC_PUSHCART": "Usar Carrinho",
	"MC_VENDING": "Comércio",
	"MG_COLDBOLT": "Lanças de Gelo",
	"MG_ENERGYCOAT": "Proteção Arcana",
	"MG_FIREBALL": "Bolas de Fogo",
	"MG_FIREBOLT": "Lanças de Fogo",
	"MG_FIREWALL": "Barreira de Fogo",
	"MG_FROSTDIVER": "Rajada Congelante",
	"MG_LIGHTNINGBOLT": "Relâmpago",
	"MG_NAPALMBEAT": "Ataque Espiritual",
	"MG_SAFETYWALL": "Escudo Mágico",
	"MG_SIGHT": "Chama Reveladora",
	"MG_SOULSTRIKE": "Espíritos Anciões",
	"MG_SRECOVERY": "Aumentar Recuperação de SP",
	"MG_STONECURSE": "Petrificar",
	"MG_THUNDERSTORM": "Tempestade de Raios",
	"MO_ABSORBSPIRITS": "Absorver Esferas Espirituais",
	"MO_BALKYOUNG": "Punhos Intensos",
	"MO_BLADESTOP": "Dilema",
	"MO_BODYRELOCATION": "Passo Etéreo",
	"MO_CALLSPIRITS": "Invocar Esfera Espiritual",
	"MO_CHAINCOMBO": "Combo Quádruplo",
	"MO_COMBOFINISH": "O Último Dragão",
	"MO_DODGE": "Cair das Pétalas",
	"MO_EXPLOSIONSPIRITS": "Fúria Interior",
	"MO_EXTREMITYFIST": "Punho Supremo de Asura",
	"MO_FINGEROFFENSIVE": "Disparo de Esferas Espirituais",
	"MO_INVESTIGATE": "Impacto Psíquico",
	"MO_IRONHAND": "Punhos de Ferro",
	"MO_KITRANSLATION": "Concessão Espiritual",
	"MO_SPIRITSRECOVERY": "Meditação",
	"MO_STEELBODY": "Corpo Fechado",
	"MO_TRIPLEATTACK": "Combo Triplo",
	"NPC_ALLHEAL": "Corrente da Vida",
	"NPC_CRITICALWOUND": "Ferimento Mortal",
	"NPC_DEFENDER": "Aura Sagrada",
	"NPC_DRAGONFEAR": "Terror Draconiano",
	"NPC_EARTHQUAKE": "Terremoto",
	"NPC_HELLJUDGEMENT": "Julgamento Infernal",
	"NPC_PULSESTRIKE": "Golpe Avassalador",
	"NPC_SLOWCAST": "Conjuração Lenta",
	"NPC_WIDEBLEEDING": "Sangria",
	"NPC_WIDECURSE": "Espírito dos Amaldiçoados",
	"NPC_WIDEFREEZE": "Beijo do Inverno",
	"NPC_WIDESILENCE": "Som do Silêncio",
	"NPC_WIDESLEEP": "Sussurro de Morfeu",
	"NPC_WIDESTUN": "Atordoamento Titânico",
	"NV_BASIC": "Habilidades Básicas",
	"NV_FIRSTAID": "Primeiros Socorros",
	"NV_TRICKDEAD": "Fingir de Morto",
	"PA_GOSPEL": "Canto de Batalha",
	"PA_PRESSURE": "Gloria Domini",
	"PA_SACRIFICE": "Sacrifício do Mártir",
	"PA_SHIELDCHAIN": "Choque Rápido",
	"PF_DOUBLECASTING": "Lanças Duplas",
	"PF_FOGWALL": "Bruma Ofuscante",
	"PF_HPCONVERSION": "Indulgir",
	"PF_MEMORIZE": "Presciência",
	"PF_MINDBREAKER": "Enlouquecedor",
	"PF_SOULBURN": "Sifão de Alma",
	"PF_SOULCHANGE": "Exalar Alma",
	"PF_SPIDERWEB": "Prisão de Teia",
	"PR_ASPERSIO": "Aspersio",
	"PR_BENEDICTIO": "B.S Sacramenti",
	"PR_GLORIA": "Glória",
	"PR_IMPOSITIO": "Impositio Manus",
	"PR_KYRIE": "Kyrie Eleison",
	"PR_LEXAETERNA": "Lex Aeterna",
	"PR_LEXDIVINA": "Lex Divina",
	"PR_MACEMASTERY": "Perícia com Maça",
	"PR_MAGNIFICAT": "Magnificat",
	"PR_MAGNUS": "Magnus Exorcismus",
	"PR_REDEMPTIO": "Martírio",
	"PR_SANCTUARY": "Santuário",
	"PR_SLOWPOISON": "Retardar Veneno",
	"PR_STRECOVERY": "Graça Divina",
	"PR_SUFFRAGIUM": "Suffragium",
	"PR_TURNUNDEAD": "Esconjurar",
	"RG_BACKSTAP": "Apunhalar",
	"RG_CLEANER": "Faxina",
	"RG_CLOSECONFINE": "Confinamento",
	"RG_COMPULSION": "Extorquir",
	"RG_FLAGGRAFFITI": "Pichar",
	"RG_GANGSTER": "Malandragem",
	"RG_GRAFFITI": "Graffiti",
	"RG_INTIMIDATE": "Rapto",
	"RG_PLAGIARISM": "Plágio",
	"RG_RAID": "Ataque Surpresa",
	"RG_SNATCHER": "Mãos Leves",
	"RG_STEALCOIN": "Afanar",
	"RG_STRIPARMOR": "Remover Armadura",
	"RG_STRIPHELM": "Remover Capacete",
	"RG_STRIPSHIELD": "Remover Escudo",
	"RG_STRIPWEAPON": "Remover Arma",
	"RG_TUNNELDRIVE": "Túnel de Fuga",
	"SA_ABRACADABRA": "Abracadabra",
	"SA_ADVANCEDBOOK": "Estudo de Livros",
	"SA_AUTOSPELL": "Desejo Arcano",
	"SA_CASTCANCEL": "Cancelar magia",
	"SA_CREATECON": "Criar Conversor Elemental",
	"SA_DELUGE": "Dilúvio",
	"SA_DISPELL": "Desencantar",
	"SA_DRAGONOLOGY": "Dragonologia",
	"SA_ELEMENTFIRE": "Mudança Elemental - Fogo",
	"SA_ELEMENTGROUND": "Mudança Elemental - Terra",
	"SA_ELEMENTWATER": "Mudança Elemental - Água",
	"SA_ELEMENTWIND": "Mudança Elemental - Vento",
	"SA_FLAMELAUNCHER": "Encantar com Chama",
	"SA_FREECAST": "Conjuração Livre",
	"SA_FROSTWEAPON": "Encantar com Geada",
	"SA_LANDPROTECTOR": "Proteger Terreno",
	"SA_LIGHTNINGLOADER": "Encantar com Ventania",
	"SA_MAGICROD": "Espelho Mágico",
	"SA_REVERSEORCISH": "Transformação Orc",
	"SA_SEISMICWEAPON": "Encantar com Terremoto",
	"SA_SPELLBREAKER": "Desconcentrar",
	"SA_VIOLENTGALE": "Furacão",
	"SA_VOLCANO": "Vulcão",
	"SM_AUTOBERSERK": "Instinto de Sobrevivência",
	"SM_BASH": "Golpe Fulminante",
	"SM_ENDURE": "Vigor",
	"SM_FATALBLOW": "Ataque Fatal",
	"SM_MAGNUM": "Impacto Explosivo",
	"SM_MOVINGRECOVERY": "Recuperar HP em Movimento",
	"SM_PROVOKE": "Provocar",
	"SM_RECOVERY": "Aumentar Recuperação de HP",
	"SM_SWORD": "Perícia com Espada",
	"SM_TWOHAND": "Perícia com Espada de Duas Mãos",
	"SN_FALCONASSAULT": "Assalto do Falcão",
	"SN_SHARPSHOOTING": "Tiro Preciso",
	"SN_SIGHT": "Visão Real",
	"SN_WINDWALK": "Caminho do Vento",
	"ST_CHASEWALK": "Espreitar",
	"ST_FULLSTRIP": "Remoção Total",
	"ST_PRESERVE": "Preservar",
	"ST_REJECTSWORD": "Instinto de Defesa",
	"TF_BACKSLIDING": "Recuar",
	"TF_DETOXIFY": "Desintoxicar",
	"TF_DOUBLE": "Ataque Duplo",
	"TF_HIDING": "Esconderijo",
	"TF_MISS": "Perícia em Esquiva",
	"TF_PICKSTONE": "Procurar Pedras",
	"TF_POISON": "Envenenar",
	"TF_SPRINKLESAND": "Chutar Areia",
	"TF_STEAL": "Furto",
	"TF_THROWSTONE": "Arremessar Pedra",
	"WS_CARTBOOST": "Impulso no Carrinho",
	"WS_CARTTERMINATION": "Choque de Carrinho",
	"WS_MELTDOWN": "Golpe Estilhaçante",
	"WS_OVERTHRUSTMAX": "Força Violentíssima",
	"WS_WEAPONREFINE": "Aprimorar Armamento",
	"WZ_EARTHSPIKE": "Coluna de Pedra",
	"WZ_ESTIMATION": "Sentido Sobrenatural",
	"WZ_FIREPILLAR": "Coluna de Fogo",
	"WZ_FROSTNOVA": "Congelar",
	"WZ_HEAVENDRIVE": "Fúria da Terra",
	"WZ_ICEWALL": "Barreira de Gelo",
	"WZ_JUPITEL": "Trovão de Júpiter",
	"WZ_METEOR": "Chuva de Meteoros",
	"WZ_QUAGMIRE": "Pântano dos Mortos",
	"WZ_SIGHTBLASTER": "Explosão Protetora",
	"WZ_SIGHTRASHER": "Supernova",
	"WZ_STORMGUST": "Nevasca",
	"WZ_VERMILION": "Ira de Thor",
	"WZ_WATERBALL": "Esfera d'Água",
};

/** O nome em portugues da habilidade `skillId` (numerico), ou o ingles do SkillInfo, ou 'Unknown Skill'. */
export function nomeDaHabilidadeParaOJogador(skillId) {
	const info = SkillInfo[skillId];
	if (!info) {
		return 'Unknown Skill';
	}
	return NOME_PT_POR_CONSTANTE[info.Name] || info.SkillName || 'Unknown Skill';
}

export default NOME_PT_POR_CONSTANTE;
